typography_spectrum: 0.09876930993050337
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.72726658009924
  lightness: 0.6043711572419852
  saturation: 0.9933002449106425
  rhythmicContrast: 0.11524711968377233
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6423676279373467
analytics:
  google: null
  facebook: null
  twitter: null
name: dle
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: DLE Digital
description: the very best in web design
purpose: []
